import { Course } from "./course";

export const jobLists: Course[] =  [{
  courseCode: "COSC1234",
  courseName: "full stack development",
  jobType: "Part-Time",
  jobVacancy: 9,
  skillsNeeded: ["Node.js, React"],
  semester: "Semester 1",
  year: 2025,
},
{
  courseCode: "COSC2234",
  courseName: "software testing",
  jobType: "Full-Time",
  jobVacancy: 4,
  skillsNeeded: ["Testings"],
  semester: "Semester 1",
  year: 2025,
},
{
  courseCode: "COSC3234",
  courseName: "usability engineering",
  jobType: "Full-Time",
  jobVacancy: 6,
  skillsNeeded: ["UI/UX"],
  semester: "Semester 2",
  year: 2025,
},
{
  courseCode: "COSC4234",
  courseName: "database concept",
  jobType: "Part-Time",
  jobVacancy: 6,
  skillsNeeded: ["SQL, DBMS"],
  semester: "Semester 1",
  year: 2025,
},
{
  courseCode: "COSC5334",
  courseName: "advanced programming",
  jobType: "Full-Time",
  jobVacancy: 3,
  skillsNeeded: ["C++, Data Structures"],
  semester: "Semester 1",
  year: 2026,
},
{
  courseCode: "COSC6234",
  courseName: "programming fundamental",
  jobType: "Part-Time",
  jobVacancy: 1,
  skillsNeeded: ["Python"],
  semester: "Semester 2",
  year: 2025,
},
{
  courseCode: "COSC7234",
  courseName: "database application",
  jobType: "Part-Time",
  jobVacancy: 1,
  skillsNeeded: ["SQL, MongoDB"],
  semester: "Semester 2",
  year: 2025,
},
{
  courseCode: "COSC7734",
  courseName: "software engineering project management",
  jobType: "Part-Time",
  jobVacancy: 1,
  skillsNeeded: ["Scrum, Agile"],
  semester: "Semester 2",
  year: 2025,
},
{
  courseCode: "COSC8237",
  courseName: "algorithms",
  jobType: "Full-Time",
  jobVacancy: 7,
  skillsNeeded: ["Python, Mathematics"],
  semester: "Semester 2",
  year: 2026,
},
{
  courseCode: "COSC8234",
  courseName: "iphone software engineering",
  jobType: "Full-Time",
  jobVacancy: 7,
  skillsNeeded: ["Swift"],
  semester: "Semester 1",
  year: 2026,
},


]